baseURL = "https://pankajniroula.com.np/"
languageCode = "en-us"
title = "Pankaj Niroula"
theme = "hugo-digital-garden-theme"

[params]
  name = "Pankaj Niroula"
  description = "Curious Explorer of Computers, Humans and Life"
  initials = "PN"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/npankaj365"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/npankaj365"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://linkedin.com/in/npankaj365"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 5


[taxonomies]
  garden_tags = 'garden_tags'
  link_tags = 'link_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'